services:
  web:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - OPENAI_API_KEY=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
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
